### ISSUE TITLE
Search implementation in the Onion Architecture

### ISSUE THREAD

**Issue by pete1854** [CodeMazeBlog/onion-architecture-aspnetcore#1]
Hi,

Thanks for a great introduction to the OA!

Do you have any suggestions on how to best implement search functionality (as described in your [Advanced Rest Concepts Series](https://github.com/CodeMazeBlog/advanced-rest-concepts-aspnetcore))? The main issue for me is your slightly different Repo implementation in the OA.

Kind regards,
Peter

**Comment by CodeMazeBlog** [comment]
Hello Peter.

Well, in our book https://code-maze.com/ultimate-aspnetcore-webapi-second-edition/?source=nav we implemented searching, sorting, and paging using OA with a full repo and service layers. Trying to share a solution here would be pretty hard to do.
