### ISSUE TITLE
How to call an external API

### ISSUE THREAD

**Issue by juleedev** [CodeMazeBlog/onion-architecture-aspnetcore#2]
Can you show an example of how to call an external API? 
For example, I have to call MS Graph as a part of my business requirements.  I'm happy to buy the book if it has clear examples on how to do that.  But I also need something in short order... that would just give an outline of how to do it.

**Comment by CodeMazeBlog** [comment]
Hi. To call an external api you have to set up your HttpClient. In our Web API book, we are not doing that, but in the security book, we do create an Identity Server, a client MVC app that uses HttpClient to consume the data from the Web API. But if you want to buy books just for that, I don't recommend them. Please go over our sales page and see all the things we offer in our books and then decide about the purchase. On our site, we have this tutorial: https://code-maze.com/httpclient-with-asp-net-core-tutorial/ that covers a lot regarding HttpClient and how to use it properly with HttpClient Factory.

**Comment by juleedev** [comment]
Sorry I should have been more specific.  It's not just an external API but MS Graph.  Graph does provide their own libraries to include in an asp.net core project.  I'll still review the sample you just provided.  but sharing this additional information in case it affects your answer.

**Comment by CodeMazeBlog** [comment]
Yeah, I understand, but the issue is that I didn't consume the MS Graph at all, so I am not sure how to help you here. Probably some sort of documentation could be beneficial here.
