### ISSUE TITLE
Why a service manager? 

### ISSUE THREAD

**Issue by juleedev** [CodeMazeBlog/onion-architecture-aspnetcore#3]
My question is what the benefit is of having the concept of a service manager?  It seems you wrap all individual services inside this class... and then when you're requesting a specific service, you have to go through this service manager.  

I also noticed that you are employing lazy loading ... so i think this means that whatever service is requested, they'll only be created when they are explicitly requested.  

I'm not a c# or .net core expert...  but it seems that if i got rid of the service manager, and only instantiated the objects when I needed them, isn't that the same thing?  I guess if the list of accounts property on the Owner class was super expensive to load for each owner, then we could lazy load that specific property.  But it seems you are lazy loading the entire class.
I'm sure I'm missing something uber simple / obvious here. 

The use case I'm thinking about if you want to change the Account service so that you inject another dependency... then the service manager now needs to know about/create that dependency and pass it in?

Thanks in advance for your time.

**Comment by CodeMazeBlog** [comment]
It would take a lot of time to explain why service manager and why is better to use DI instead of instantiating your individual services (repositories as well). You can always check our articles on DI (dependency injection) and see all the benefits there. And yes, LazyLoad is exactly for that purpose.

**Comment by aishwhensheds** [comment]
Hie,

In service mange if we want to pass reference of let say AccountService to OwnerService then how we will do that?

will It will be like showing below?
 public ServiceManager(IRepositoryManager repositoryManager)
        {
        _lazyOwnerService = new Lazy<IOwnerService>(() => new OwnerService(repositoryManager, _lazyAccountService.Value));

            _lazyAccountService = new Lazy<IAccountService>(() => new AccountService(repositoryManager));
        }
  
What if we have to pass around 5 to 6 service reference 
Thanks
