### ISSUE TITLE
In Service Manger passing references of other service.

### ISSUE THREAD

**Issue by aishwhensheds** [CodeMazeBlog/onion-architecture-aspnetcore#4]
Hie, 

In service mange if we want to pass reference of let say AccountService to OwnerService then how we will do that?

will It will be like showing below?
 public ServiceManager(IRepositoryManager repositoryManager)
        {
        
_lazyOwnerService = new Lazy<IOwnerService>(() => new OwnerService(repositoryManager, **_lazyAccountService.Value**));
            _lazyAccountService = new Lazy<IAccountService>(() => new AccountService(repositoryManager));
}
  
What if we have to pass around 5 to 6 service reference 
Thanks

_Originally posted by @aishwhensheds in https://github.com/CodeMazeBlog/onion-architecture-aspnetcore/issues/3#issuecomment-1703810636_

**Comment by CodeMazeBlog** [comment]
Services shouldn't know about each other. There is really no point that you have a service with the exact logic needed in another service. If you have a similar case, then probably you will need any helper class with the extracted logic and injected into both services. Or you should simply call the same repository methods in both services. Again, having one method in one service and then trying to use that same method from one service in another service means that something is wrong with the architecture.
